// src/data.js
export const ships = [
{ name: '890 Jump', capacity: 950 },
{ name: 'A2 Hercules', capacity: 234 },
{ name: 'Carrack', capacity: 456 },
{ name: 'C2 Hercules', capacity: 696 },
{ name: 'Caterpillar', capacity: 576 },
{ name: 'Caterpillar Pirate Edition', capacity: 564 },
{ name: 'Constellation Andromeda', capacity: 96 },
{ name: 'Constellation Aquila', capacity: 96 },
{ name: 'Constellation Phoenix', capacity: 96 },
{ name: 'Constellation Phoenix Emerald', capacity: 96 },
{ name: 'Constellation Taurus', capacity: 168 },
{ name: 'Corsair', capacity: 72 },
{ name: 'Cutlass Black', capacity: 46 },
{ name: 'Freelancer', capacity: 66 },
{ name: 'Freelancer MAX', capacity: 120 },
{ name: 'Hull A', capacity: 64 },
{ name: 'M2 Hercules', capacity: 468 },
{ name: 'Mercury Star Runner', capacity: 114 },
{ name: '600i Explorer', capacity: 40 },
{ name: 'StarLancer MAX', capacity: 224 },
];

export const loadingPlaces = [
'Seraphim Station',
'Everus Harbor',
'Baijini Point',
'Port Tressler',
'ARC-L1',
'ARC-L3',
'ARC-L4',
'ARC-L5',
'CRU-L1',
'CRU-L3',
'CRU-L4',
'CRU-L5',
'HUR-L1',
'HUR-L2',
'HUR-L3',
'HUR-L4',
'HUR-L5',
'MIC-L2',
'MIC-L3',
'MIC-L4',
'MIC-L5',
'JP vers Pyro',
'JP vers Magnus',
'JP vers Terra',
'Afterlife',
'ArcCorp Mining Area 045',
'ArcCorp Mining Area 048',
'ArcCorp Mining Area 056',
'ArcCorp Mining Area 061',
'ArcCorp Mining Area 141',
'ArcCorp Mining Area 157',
'Archibald Station',
'Arid Reach',
'Ashland',
'Benson Mining Outpost',
'Blackrock Exchange',
'Bountiful Harvest Hydroponics',
'Brios Breaker Yard',
'Bud Growery',
'Bueno Ravine',
'Bullocks Reach',
'Canard View',
'Carvers Ridge',
'Chawlas Beach',
'Connors',
'Covalex Distribution Center S4DC05',
'Deakins Research Outpost',
'Dingers Depot',
'Elsewhere',
'Fallow Field',
'FEO Canyon Depot',
'Frigid Knot',
'Gallete Family Farms',
'Goners Deal',
'Good Times Temple',
'Gray Gardens Depot',
'HDMS-Bezdek',
'HDMS-Edmond',
'HDMS-Hadley',
'HDMS-Hahn',
'HDMS-Lathan',
'HDMS-Norgaard',
'HDMS-Oparei',
'HDMS-Perlman',
'HDMS-Pinewood',
'HDMS-Ryder',
'HDMS-Stanhope',
'HDMS-Thedus',
'Hickes Research Outpost',
'HSOF-Palomar',
'Humboldt Mines',
'Jacksons Swap',
'Kabirs Post',
'Kinder Plots',
'Kudre Ore',
'Last Ditch',
'Last Landings',
'Lost and Found',
'Loveridge Mineral Reserve',
'MT DataCenter 2UB-RB9-5',
'MT DataCenter 4HJ-LVE-A',
'MT DataCenter 5WQ-R2V-C',
'MT DataCenter 8FK-Q2X-K',
'MT DataCenter D79-ECG-R',
'MT DataCenter E2Q-NSG-Y',
'MT DataCenter KH3-AAE-L',
'MT DataCenter L8P-JUC-8 (offline)',
'MT DataCenter QVX-J88-J',
'MT DataCenter TMG-XEV-2',
'MT OpCenter TLI-4',
'Narenas Rest',
'NT-999-XVI',
'NT-999-XX',
'NT-999-XXII',
'Nuen Waste Management',
'Ostlers Claim',
'Outpost 54',
'Prophets Peak',
'Prospect Depot',
'Rayari Anvik Research Outpost',
'Rayari Cantwell Research Outpost',
'Rayari Deltana Research Outpost',
'Rayari Kaltag Research Outpost',
'Rayari Livengood Research Outpost',
'Rayari McGrath Research Outpost',
'Rough Landing',
'Rustville',
'Sacrens Plot',
'Scarpers Turn',
'Security Depot Lyria-1',
'Security Post Criska',
'Security Post Dipur',
'Security Post Lespin',
'Security Post Moluto',
'Security Post Opal',
'Security Post Prashad',
'Security Post Thaquray',
'Security Post Wan',
'Seers Canyon',
'Shady Glen Farms',
'Shepherds Rest',
'Shubin Mining Facility SAL-2',
'Shubin Mining Facility SAL-5',
'Shubin Mining Facility SCD-1',
'Shubin Mining Facility SM0-10',
'Shubin Mining Facility SM0-13',
'Shubin Mining Facility SM0-18',
'Shubin Mining Facility SM0-22',
'Shubin Mining Facility SMCa-6',
'Shubin Mining Facility SMCa-8',
'Shubin Processing Facility SPAL-12',
'Shubin Processing Facility SPAL-16',
'Shubin Processing Facility SPAL-21',
'Shubin Processing Facility SPAL-3',
'Shubin Processing Facility SPAL-7',
'Shubin Processing Facility SPAL-9',
'Shubin Processing Facility SPMC-1',
'Shubin Processing Facility SPMC-10',
'Shubin Processing Facility SPMC-11',
'Shubin Processing Facility SPMC-14',
'Shubin Processing Facility SPMC-3',
'Shubin Processing Facility SPMC-5',
'Slowburn Depot',
'Stags Rut',
'Stash House (Cellin)',
'Stonetree',
'Sunset Mesa',
'Supply Gap',
'Talarine Divide Aid Shelter',
'Teddys Playhouse',
'Terra Mills HydroFarm',
'The Garden',
'The Golden Riviera',
'The Necropolis',
'The Orphanage',
'The Pit',
'The Yard',
'TPF',
'Tram & Myers Mining',
'Unnamed abandoned outpost (Cellin)',
'Unnamed abandoned outpost (Daymar)',
'Unnamed abandoned outpost (Yela)',
'Utopia',
'Washout',
'Watchers Depot',
'Wheelers',
'Wiley Flats',
'Windfall',
'Yangs Place',

];

export const resourceTypes = [
  'Agricium',
  'Agricium (Ore)',
  'Aluminum',
  'Aluminum (Ore)',
  'Borase',
  'Borase (Ore)',
  'Carbon',
  'Cobalt',
  'Copper',
  'Copper (Ore)',
  'Gold',
  'Gold (Ore)',
  'Iron',
  'Iron (Ore)',
  'Mercury',
  'Riccite',
  'Silicon',
  'Stileron',
  'Tin',
  'Titanium',
  'Titanium (Ore)',
  'Tungsten',
  'Tungsten (Ore)',
  "Xa' Pyen",
  'Agricultural Supplies',
  'DCSR2',
  'Ranta Dung',
  'Altruciatoxin',
  'Distilled Spirits',
  'E\'tam',
  'Gasping Weevil Eggs',
  'Maze',
  'Neon',
  'Osoian Hides',
  'Revenant Tree Pollen',
  'SLAM',
  'Stims',
  'WiDow',
  'Ammonia',
  'Argon',
  'Astatine',
  'Chlorine',
  'Fluorine',
  'Helium',
  'Hydrogen',
  'HydrogenFuel',
  'Iodine',
  'Methane',
  'Nitrogen',
  'Partillium',
  'Pressurized Ice',
  'QuantumFuel',
  'Aphorite',
  'Beryl',
  'Beryl (Raw)',
  'Bexalite',
  'Bexalite (Raw)',
  'Corundum',
  'Corundum (Raw)',
  'Diamond',
  'Diamond (Raw)',
  'Dolivine',
  'Hadanite',
  'Hephaestanite',
  'Hephaestanite (Raw)',
  'Janalite',
  'Laranite',
  'Laranite (Raw)',
  'Potassium',
  'Quantainium',
  'Quantainium (Raw)',
  'Quartz',
  'Quartz (Raw)',
  'Taranite',
  'Taranite (Raw)',
  'Atlasium',
  'Beradom',
  'Dymantium',
  'Feynmaline',
  'Glacosite',
  'Steel',
  'Compboard',
  'Scrap',
  'Fresh Food',
  'Human Food Bars',
  'Processed Food',
  'Medical Supplies',
  'Recycled Material Composite',
  'Waste',
  'Ship Ammunition'

];

export const destinations = [
'Seraphim Station',
'Everus Harbor',
'Baijini Point',
'Port Tressler',
'ARC-L1',
'ARC-L3',
'ARC-L4',
'ARC-L5',
'CRU-L1',
'CRU-L3',
'CRU-L4',
'CRU-L5',
'HUR-L1',
'HUR-L2',
'HUR-L3',
'HUR-L4',
'HUR-L5',
'MIC-L2',
'MIC-L3',
'MIC-L4',
'MIC-L5',
'JP vers Pyro',
'JP vers Magnus',
'JP vers Terra',
'Afterlife',
'ArcCorp Mining Area 045',
'ArcCorp Mining Area 048',
'ArcCorp Mining Area 056',
'ArcCorp Mining Area 061',
'ArcCorp Mining Area 141',
'ArcCorp Mining Area 157',
'Archibald Station',
'Arid Reach',
'Ashland',
'Benson Mining Outpost',
'Blackrock Exchange',
'Bountiful Harvest Hydroponics',
'Brios Breaker Yard',
'Bud Growery',
'Bueno Ravine',
'Bullocks Reach',
'Canard View',
'Carvers Ridge',
'Chawlas Beach',
'Connors',
'Covalex Distribution Center S4DC05',
'Deakins Research Outpost',
'Dingers Depot',
'Elsewhere',
'Fallow Field',
'FEO Canyon Depot',
'Frigid Knot',
'Gallete Family Farms',
'Goners Deal',
'Good Times Temple',
'Gray Gardens Depot',
'HDMS-Bezdek',
'HDMS-Edmond',
'HDMS-Hadley',
'HDMS-Hahn',
'HDMS-Lathan',
'HDMS-Norgaard',
'HDMS-Oparei',
'HDMS-Perlman',
'HDMS-Pinewood',
'HDMS-Ryder',
'HDMS-Stanhope',
'HDMS-Thedus',
'Hickes Research Outpost',
'HSOF-Palomar',
'Humboldt Mines',
'Jacksons Swap',
'Kabirs Post',
'Kinder Plots',
'Kudre Ore',
'Last Ditch',
'Last Landings',
'Lost and Found',
'Loveridge Mineral Reserve',
'MT DataCenter 2UB-RB9-5',
'MT DataCenter 4HJ-LVE-A',
'MT DataCenter 5WQ-R2V-C',
'MT DataCenter 8FK-Q2X-K',
'MT DataCenter D79-ECG-R',
'MT DataCenter E2Q-NSG-Y',
'MT DataCenter KH3-AAE-L',
'MT DataCenter L8P-JUC-8 (offline)',
'MT DataCenter QVX-J88-J',
'MT DataCenter TMG-XEV-2',
'MT OpCenter TLI-4',
'Narenas Rest',
'NT-999-XVI',
'NT-999-XX',
'NT-999-XXII',
'Nuen Waste Management',
'Ostlers Claim',
'Outpost 54',
'Prophets Peak',
'Prospect Depot',
'Rayari Anvik Research Outpost',
'Rayari Cantwell Research Outpost',
'Rayari Deltana Research Outpost',
'Rayari Kaltag Research Outpost',
'Rayari Livengood Research Outpost',
'Rayari McGrath Research Outpost',
'Rough Landing',
'Rustville',
'Sacrens Plot',
'Scarpers Turn',
'Security Depot Lyria-1',
'Security Post Criska',
'Security Post Dipur',
'Security Post Lespin',
'Security Post Moluto',
'Security Post Opal',
'Security Post Prashad',
'Security Post Thaquray',
'Security Post Wan',
'Seers Canyon',
'Shady Glen Farms',
'Shepherds Rest',
'Shubin Mining Facility SAL-2',
'Shubin Mining Facility SAL-5',
'Shubin Mining Facility SCD-1',
'Shubin Mining Facility SM0-10',
'Shubin Mining Facility SM0-13',
'Shubin Mining Facility SM0-18',
'Shubin Mining Facility SM0-22',
'Shubin Mining Facility SMCa-6',
'Shubin Mining Facility SMCa-8',
'Shubin Processing Facility SPAL-12',
'Shubin Processing Facility SPAL-16',
'Shubin Processing Facility SPAL-21',
'Shubin Processing Facility SPAL-3',
'Shubin Processing Facility SPAL-7',
'Shubin Processing Facility SPAL-9',
'Shubin Processing Facility SPMC-1',
'Shubin Processing Facility SPMC-10',
'Shubin Processing Facility SPMC-11',
'Shubin Processing Facility SPMC-14',
'Shubin Processing Facility SPMC-3',
'Shubin Processing Facility SPMC-5',
'Slowburn Depot',
'Stags Rut',
'Stash House (Cellin)',
'Stonetree',
'Sunset Mesa',
'Supply Gap',
'Talarine Divide Aid Shelter',
'Teddys Playhouse',
'Terra Mills HydroFarm',
'The Garden',
'The Golden Riviera',
'The Necropolis',
'The Orphanage',
'The Pit',
'The Yard',
'TPF',
'Tram & Myers Mining',
'Unnamed abandoned outpost (Cellin)',
'Unnamed abandoned outpost (Daymar)',
'Unnamed abandoned outpost (Yela)',
'Utopia',
'Washout',
'Watchers Depot',
'Wheelers',
'Wiley Flats',
'Windfall',
'Yangs Place',

];
